### ISSUE TITLE
Don't use inline scripts

### ISSUE THREAD

**Issue by buschtoens** [josemarluedke/ember-cli-segment#6]
When sane [**Content Security Policy**](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Keywords) directives are enabled, this addon doesn't work, as it includes the tracking snippet [as an inline script](https://github.com/josemarluedke/ember-cli-segment/blob/master/index.js#L14-18).

The snippet should preferably be added to `vendor.js`. What are your thoughts on this?

**Comment by josemarluedke** [comment]
Hey, thank you for reporting it.

I would love to see a pull request solving these issues.

**Comment by karellm** [comment]
It looks like the only way to go around this issue is with CSP 1.1 (still a draft) that introduce support for nonce and hashes. In other words, you can still disable `unsafe-inline` while authorizing it for specific scripts. Really nice, but not well supported (if at all).

We are left with two solutions:

1/ Enable `unsafe-inline` in our CSP. Removing for the entire app the XSS security layer. It sucks!

2/ Only use services that give you a single load script. Most don't do because it limits their feature set. But with `<script src="//segment.com/script.js" async="async" data-write-key="XYZ"></script>` we should be good.

I reached out to Segment to see if they offer 2/. I will keep you posted if they do.

**Comment by abradner** [comment]
Any news @karellm ?

**Comment by karellm** [comment]
@abradner So basically it is too big a battle. Even if you get (and the Segment developer I talked to seemed willing to help) Segment with a single script tag, you will still get to make the integrations work with CSP.

We decided to drop Segment altogether, to be honest it is a big rip off! It doesn't store your data unless you pay 400$/mo, it doesn't let you backport data unless you upgrade to the Business plan (who knows how much it costs), it doesn't proxy all the analytics in the frontend (to send event only once rather than once per integration). So what exactly does Segment do? Well I have no idea because even the "easy integration setup" argument just fell apart with CSP, you need an engineer intervention to get them to work... I would not waste time with Segment at all.

**Comment by josemarluedke** [comment]
Closing this since there are no movements on this anymore.
